//tealium universal tag - utag.8 ut4.0.201808282045, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.plugin_fn=function(pluginOb,data,plugin_name){var dataObj;plugin_name=plugin_name||pluginOb;if(u.data['plugins_'+pluginOb]==="true"){u.data.plugins[plugin_name]=u.data.plugins[plugin_name]||{};dataObj=u.data.plugins[plugin_name];if(typeof(data)==="string"){dataObj.src=dataObj.src||data;}else{for(var i in utag.loader.GV(data)){dataObj[i]=dataObj[i]||data[i];}}}else{try{delete u.data.plugins[plugin_name];}catch(e){u.data.plugins[plugin_name]=undefined;}}};u.map={"video_event":"WT.clip_ev","video_percent":"WT.clip_perc","media_name":"WT.clip_n","vid_clip_id":"WT.clip_id","video_duration":"WT.clip_duration","page_name":"WT.ti,WT.z_snaps_hdg","wtb_category":"WT.z_wtbcategory","wtb_prod_selector":"WT.z_wtbprodsel","wtb_event":"WT.z_wtbevent","conversion_step":"WT.si_cs","wtb_channel":"WT.z_wtbchannel","scenario_name":"WT.si_n","step_number":"WT.si_x","wtb_dealer":"WT.z_wtbdealer","search_phrase":"WT.oss_wtb30,WT.oss","search_results":"WT.oss_r_wtb30,WT.oss_r","event_name":"WT.cg_s","event_type":"WT.cg_n","wt_plugin_tealiumevents":"plugins.tealiumevents.src","ad_click":"WT.ac","dom.pathname":"DCS.dcsuri","event_id":"WT.dl","snaps_remove_refinement":"WT.z_fuzeattclose","gallery_level":"WT.z_fuzegallvl","product_sku":"WT.pn_sku","search_result_click":"WT.z_sresult","pdp_tab":"WT.z_fuzepdptab","breadcrumb_link	":"WT.z_fuzebrlink","document_download":"WT.z_fuzepdpdl","product_thumbnail_click":"WT.z_fuzepdptn","wtb_click":"WT.z_wtbclick","compare_product":"WT.z_addcompare"};u.extend=[function(a,b){try{if(1){b['wt_plugin_mmm_downloads']='//solutions.3m.com/3MContentRetrievalAPI/BlobServlet?assetId=1361806296197&assetType=MMM_Image&blobAttribute=ImageFile&x=a.js'}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['wt_plugin_scroll_depth']='//www.3m.com/3m_theme_assets/themes/3MTheme/assets/scripts/src/kungfu/webtrends/mmm_scroll_depth.js'}}catch(e){utag.DB(e)}},function(a,b){try{window.dcsMultiTrack=function(){$msg('Calls to dcsMultiTrack should only be done upon events, not page load. Contact eMetrics');}
window.dcsMultiTrackHREF=function(){$msg('dcsMultiTrackHREF() is a deprecated function and should be updated. Contact eMetrics');}
window.dcsMultiTrackImage=function(){$msg('dcsMultiTrackImage() is a deprecated function and should be updated. Contact eMetrics');}
window.dcsMultiTrackForm=function(){$msg('dcsMultiTrackImage() is a deprecated function and should be updated. Contact eMetrics');}
window.dcsMultiTrackArray=function(){$msg('dcsMultiTrackArray() is a deprecated function and should be updated. Contact eMetrics');}
window.dcsOffsite=function(){$msg('dcsOffsite() is a deprecated function and should be updated. Contact eMetrics');}
window.sendPageInfoToSDC=function(){}
DCS.dcsuri=window.location.pathname+window.location.search+window.location.hash;}catch(e){utag.DB('Failed to include deprecated functions: '+e);}},function(a,b){try{window.$msg=function(msg){if(window.console&&window.console.log){window.console.log(msg);}}
window.$db=function(msg,param){if(!param){var param='webtrends';}
if($u.debug){if($u.debug.indexOf(param)!=-1){if(window.console&&window.console.log)window.console.log(msg);}}};window.readMetatagValue=function(a){var b,c,d,e,f,g;e="",f=0,document.all?b=document.all.tags("meta"):document.documentElement&&(b=document.getElementsByTagName("meta"));var h=b.length;for(g=0;g<h;g++){c=b[g].name;if(c.toUpperCase()==a.toUpperCase())return f=1,""+b[g].content}
if(f===0)return"No Meta Tag Found"}
window.getURLStringWT=function(){var vars=[],urlHash;var urlHashes=window.location.href.slice(window.location.href.indexOf('?')+1).split('&');for(var i=0;i<urlHashes.length;i++){urlHash=urlHashes[i].split('=');vars.push(urlHash[0]);vars[urlHash[0]]=urlHash[1];}
return vars;}
window.$u=getURLStringWT();window.getSiteLocale=function(){var site_locale='en_WW',site_locale=readMetatagValue('DCSExt.Locale');$db('     Site Locale: '+site_locale,'webtrends');return site_locale;}}catch(e){utag.DB('Error inserting utility functions: '+e);}},function(a,b){try{if(1){try{b['wt_plugins_heatmap']={src:"//s.webtrends.com/js/webtrends.hm.js",hmurlparams:"p,loc,plmlblid,pc,N,rt,sku,PC_7_RJH9U52300N9F0IU7S8MC91KP3000000_nid,PC_7_RJH9U5230GGA50II31R7LV2AG7000000_nid,PC_7_RJH9U523080QE0IIHEICN90GC1000000_nid"}}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){window.location.href.indexOf("+8720539")>=0&&$("head").append("<meta name='DCSext.site' content='SGB_WorkerHealth&Safety_LA'><meta name='DCSext.ewcd_url' content='Z6_79L2HO02KO3D30A951KGS60004'><meta name='DCSext.division' content='Personal Safety Division'><meta name='DCSext.bigB' content='Safety & Graphics Business Group'>");}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":"//s.webtrends.com/js/webtrends.min.js","dcsid":"dcsrqbu6w100008adnpdxh534_8x8z","testdcsid":"","domain":"statse.webtrendslive.com","timezone":"-5","fpcdom":""||("."+utag.cfg.domain),"onsitedoms":""||utag.cfg.domain,"download":"true","offsite":"true","anchor":"true","javascript":"true","trimoffsiteparams":"true","enabled":"true","downloadtypes":"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip,mp4","i18n":"true","fpc":"WT_FPC","paidsearchparams":"gclid","splitvalue":"","preserve":"true","navigationtag":"div,table","adimpressions":"true","adsparam":'WT.ac',"cookieexpires":46656000000,"plugins":{},"plugins_ads":"false","plugins_fb":"true","plugins_yt":"true","plugins_hm":"true","plugins_replicate":"true","test_domains":",,"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.data.hasOwnProperty(e[f])||e[f].indexOf("plugins.")===0){if(e[f].indexOf("plugins.")===0){g=e[f].split(".");if(g.length===3){u.data.plugins[g[1]]=u.data.plugins[g[1]]||{};u.data.plugins[g[1]][g[2]]=b[d];}else if(g.length===2){u.data.plugins[g[1]]=b[d];}}else{u.data[e[f]]=b[d];}}else{if(b[d]instanceof Array){c[e[f]]=b[d].join(';');}else{c[e[f]]=b[d];}}}}}
u.loader_cb=function(a,b,c){if(!u.initialized){u.initialized=true;if(u.data.test_domains.replace(/\s/g,"").indexOf(","+location.hostname+',')>-1){u.data.dcsid=u.data.testdcsid;}
u.plugin_fn("ads","//s.webtrends.com/js/webtrends.ads.js");u.plugin_fn("fb","//s.webtrends.com/js/webtrends.fb.js","facebook");u.plugin_fn("yt","//s.webtrends.com/js/webtrends.yt.js");u.plugin_fn("hm","//s.webtrends.com/js/webtrends.hm.js");u.plugin_fn("replicate",{src:"//s.webtrends.com/js/webtrends.replicate.js",servers:[{domain:"scs.webtrends.com"}],callbackTimeout:200});u.o=new Webtrends.dcs().init({paidsearchparams:u.data.paidsearchparams,splitvalue:c["WT.sp"]||u.data.splitvalue,dcsid:c["dcsid"]||u.data.dcsid,domain:u.data.domain,fpc:u.data.fpc,fpcdom:u.data.fpcdom,timezone:parseInt(u.data.timezone),i18n:(u.data.i18n==="true"),offsite:(u.data.offsite==="true"),onsitedoms:u.data.onsitedoms,downloadtypes:u.data.downloadtypes,download:(u.data.download==="true"),anchor:(u.data.anchor==="true"),javascript:(u.data.javascript==="true"),navigationtag:u.data.navigationtag,adimpressions:(u.data.adimpressions==="true"),adsparam:u.data.adsparam,trimoffsiteparams:(u.data.trimoffsiteparams==="true"),enabled:(u.data.enabled==="true"),cookieexpires:parseInt(u.data.cookieexpires),preserve:(u.data.preserve==="true"),plugins:u.data.plugins});}
if(a=="link"){if(typeof b["link_text"]!="undefined"&&typeof c["WT.ti"]=="undefined"){c["WT.ti"]=b["link_text"];}
if(typeof c["WT.dl"]=="undefined"||c["WT.dl"]=="0"){c["WT.dl"]="99";}}
Webtrends.multiTrack({args:c});};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":'utag_8'});}}
}};utag.o[loader].loader.LOAD(id);}("8","3m.es-mx"));}catch(error){utag.DB(error);}
