//tealium universal tag - utag.223 ut4.0.201911042159, Copyright 2019 Tealium.com Inc. All Rights Reserved.
var dnbvid={ajax:function(B,A){var postBody=arguments[2]||"",callbackFunction=A,request=navigator.userAgent.match(/MSIE 9.0/i)?(xdr=new XDomainRequest,xdr.onload=function(){callbackFunction(200,xdr.responseText)},xdr):!!window.XMLHttpRequest&&new XMLHttpRequest;try{if(request){var C=request;C.onreadystatechange=function(){4==request.readyState&&callbackFunction(request.status,request.responseText)},""!==postBody?(C.open("POST",B,!0),C.setRequestHeader("X-Requested-With","XMLHttpRequest"),C.setRequestHeader("Content-type","application/x-www-form-urlencoded"),C.setRequestHeader("Connection","close")):C.open("GET",B,!0),C.withCredentials=!0,C.send(postBody)}}catch(e){callbackFunction(200,'{"status": "404", "message":"not found"}')}},getData:function(api,type,resptype,callback){var url=location.protocol+"//"+api+".d41.co/api/?req="+api+"&form="+type;this.ajax(url,function(status,resp){if(200==status){var response=JSON.parse(resp);return 200==response.status?void callback("raw"==resptype?resp:response):404==response.status?void callback("raw"==resptype?resp:response):402==response.status?void callback("raw"==resptype?resp:response):void console.log("dnb_getData: "+response.status+" - "+response.message)}
console.log("dnb_getData: unexpected status:"+status)})}};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//api4920.d41.co/sync/"
};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var dnb_sync=document.createElement('script');dnb_sync.type='text/javascript';dnb_sync.src='https://api4920.d41.co/sync/';document.getElementsByTagName('head')[0].appendChild(dnb_sync);try{dnbvid.getData("api4920","json","t",function(dnb_Data){s.linkTrackVars="eVar90,eVar91,eVar92";s.eVar90=dnb_Data.duns+":"+dnb_Data.companyName+":"+dnb_Data.companyMsa+":"+dnb_Data.companyCountry+":"+dnb_Data.parentDuns+":"+dnb_Data.domesticUltimateDuns;s.eVar91=dnb_Data.ultimateDuns+":"+dnb_Data.industryNaics+":"+dnb_Data.salesAnnual+":"+dnb_Data.employeesInAllLocations+":"+dnb_Data.jobFunction+":"+dnb_Data.jobSeniority;if(dnb_Data.customAttributes&&dnb_Data.customAttributes.suspectIsp=="y"){s.eVar92="true";}else{s.eVar92="false";}
s.tl(true,"o","DNB data passed");});}catch(e){console.log(e);}
u.loader_cb=function(){u.initialized=true;};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_223'});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("223","3m.es-mx");}catch(error){utag.DB(error);}
